### ISSUE TITLE
not work plugin with SaberFactions 

### ISSUE THREAD

**Issue by Distolfix** [bsalha1/Printer#10]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.getRelationTo(Lcom/massivecraft/factions/iface/RelationParticipator;)Lcom/massivecraft/factions/perms/Relation;
        at com.reliableplugins.printer.hook.territory.factions.FactionsHook_UUID_v0_2_1.isNonTerritoryMemberNearby(FactionsHook_UUID_v0_2_1.java:68) ~[?:?]
        at com.reliableplugins.printer.commands.CommandOn.execute(CommandOn.java:47) ~[?:?]
        at com.reliableplugins.printer.commands.CommandHandler.onCommand(CommandHandler.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-Pa

i have this error when i use this plugin with SaberFactions and not work the plgin

**Comment by bsalha1** [comment]
[https://www.mediafire.com/file/luymh94hgrrmewo/Printer-LATEST.jar/file](url) here is a pre-release of the next version. It should work although I'm not 100% done with the update but this will fix your error.

**Comment by bsalha1** [comment]
Let me know if it's fixed
