### ISSUE TITLE
[BUG] Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by Drc-DEV** [bsalha1/Printer#22]
git-Paper-263 MC 1.17.1
Printer 3.0

Whenever I hit a player in a pvp disabled region this error gets spammed:
```
[17:28:15 ERROR]: [Printer] Unhandled exception occured in onPacketReceiving(PacketEvent) for Printer
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:727) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.reliableplugins.printer.hook.packets.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:37) ~[Printer-3.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) [ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at protocolsupport.protocol.PacketDataCodecImpl.writeServerboundInternal(PacketDataCodecImpl.java:114) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.PacketDataCodecImpl$2.read(PacketDataCodecImpl.java:45) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.PacketDataCodecImpl$ServerBoundPacketDataProcessor.process(PacketDataCodecImpl.java:216) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.PacketDataCodecImpl.writeServerbound(PacketDataCodecImpl.java:72) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.packet.middle.serverbound.play.MiddleUseEntity.write(MiddleUseEntity.java:27) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode0(ServerBoundMiddlePacket.java:23) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.packet.middle.ServerBoundMiddlePacket.decode(ServerBoundMiddlePacket.java:12) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:31) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:20) [ProtocolSupport-648.jar:?]
        at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:8) [ProtocolSupport-648.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [patched_1.17.1.jar:git-Paper-266]
        at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:23) [ProtocolSupport-648.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43) [ProtocolSupport-648.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-266]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 8177.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:271) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        ... 65 more
Caused by: java.lang.RuntimeException: An internal error occured.
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:240) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        ... 65 more
Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2287) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.level.WorldServer.b(WorldServer.java:1724) ~[patched_1.17.1.jar:git-Paper-266]
        at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:240) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib-531.jar:4.7.1-SNAPSHOT-b531]
        ... 65 more
[17:28:15 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayInUseEntity@5fa538d0[
    a=8177
    b=net.minecraft.network.protocol.game.PacketPlayInUseEntity$1@4ac0c440
    c=false
  ]
  ```

**Comment by bsalha1** [comment]
Sorry for the extremely long wait, but I just fixed this with version 3,2.
