### ISSUE TITLE
Please add the support for 1.16.4(NMS 1_16_R3)

### ISSUE THREAD

**Issue by ahdg6** [bsalha1/Printer#3]
[15:18:43 Error]: Error occurred while enabling Printer v2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net.minecraft.server.v1_16_R2.IChatBaseComponent
	at com.reliableplugins.printer.Printer.setupNMS(Printer.java:227) ~[?:?]
	at com.reliableplugins.printer.Printer.onEnable(Printer.java:104) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-277]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-277]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-277]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-277]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-277]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-277]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-277]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-277]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-277]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3112/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.4.jar:git-Paper-277]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-277]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1185) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1100) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1083) ~[?:?]
	... 13 more

**Comment by bsalha1** [comment]
I will do this today in a few hours.
